### ISSUE TITLE
程序报错RuntimeError: The size of tensor a (288) must match the size of tensor b (320) at non-singleton dimension 1

### ISSUE THREAD

**Issue by coldlarry** [lmbxmu/FilterSketch#3]
old is Conv2d(32, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),new is Conv2d(32, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False) 

Traceback (most recent call last):   File "pruning.py", line 186, in <module>     
sketch_filter = sketch_matrix(m0.weight.data, l, dim=0,weight_norm_method='l2')   
File "pruning.py", line 58, in sketch_matrix     
sigmaSquare = sigmaSquareDiag - torch.eye(l) * torch.sum(theta) 

当我想把原本640的卷积核剪枝为320个时，函数sketch_matrix会报如上错误，但其他地方是不会报错的。实在不知道，是因为程序漏洞报错，还是说因为这640个卷积核的确无法变为320个？

**Comment by lmbxmu** [comment]
运行指令发来

**Comment by lmbxmu** [comment]
> old is Conv2d(32, 640, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False),new is Conv2d(32, 320, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
> 
> Traceback (most recent call last): File "pruning.py", line 186, in
> sketch_filter = sketch_matrix(m0.weight.data, l, dim=0,weight_norm_method='l2')
> File "pruning.py", line 58, in sketch_matrix
> sigmaSquare = sigmaSquareDiag - torch.eye(l) * torch.sum(theta)
> 
> 当我想把原本640的卷积核剪枝为320个时，函数sketch_matrix会报如上错误，但其他地方是不会报错的。实在不知道，是因为程序漏洞报错，还是说因为这640个卷积核的确无法变为320个？

运行指令发来

**Comment by coldlarry** [comment]
你好呀作者，我是把你的代码用在了其他非分类模型的剪枝上，使用时并没有修改你的sketch_martrix函数。 刚才说的那个问题，我感觉更有可能是程序无法从640个卷积核丢掉320个卷积核？？？  因为当我把程序改为从640个卷积核，剪到剩下480个卷积核时，程序不会报错。 如果是剩下320个卷积，就会报错。 我还尝试随机生成一个张量，去使用sketch_martrix函数，如果剪的比例太大，也会出现这个问题。       想问一下，大佬是否有修改程序解决这种问题的好办法？

**Comment by lmbxmu** [comment]
> 你好呀作者，我是把你的代码用在了其他非分类模型的剪枝上，使用时并没有修改你的sketch_martrix函数。 刚才说的那个问题，我感觉更有可能是程序无法从640个卷积核丢掉320个卷积核？？？ 因为当我把程序改为从640个卷积核，剪到剩下480个卷积核时，程序不会报错。 如果是剩下320个卷积，就会报错。 我还尝试随机生成一个张量，去使用sketch_martrix函数，如果剪的比例太大，也会出现这个问题。 想问一下，大佬是否有修改程序解决这种问题的好办法？

=========================================================
“进行SVD时，矩阵的行数要小于列数，这里l代表矩阵的行数，oriweight.size(1) * oriweight.size(2) * oriweight.size(3)就是代表矩阵的列数，所以要求满足 l < oriweight.size(1) * oriweight.size(2) * oriweight.size(3)这个条件才进行sketch“
=========================================================
你看下这个条件是否满足，如果满足是不应该会出现问题的. 否则在分类网络上在高剪枝率下也应该要有这个问题才对。

**Comment by lmbxmu** [comment]
> 你好呀作者，我是把你的代码用在了其他非分类模型的剪枝上，使用时并没有修改你的sketch_martrix函数。 刚才说的那个问题，我感觉更有可能是程序无法从640个卷积核丢掉320个卷积核？？？ 因为当我把程序改为从640个卷积核，剪到剩下480个卷积核时，程序不会报错。 如果是剩下320个卷积，就会报错。 我还尝试随机生成一个张量，去使用sketch_martrix函数，如果剪的比例太大，也会出现这个问题。 想问一下，大佬是否有修改程序解决这种问题的好办法？


--------------------------------------------------------------------------------------------------------
“进行SVD时，矩阵的行数要小于列数，这里l代表矩阵的行数，oriweight.size(1) * oriweight.size(2) * oriweight.size(3)就是代表矩阵的列数，所以要求满足 l < oriweight.size(1) * oriweight.size(2) * oriweight.size(3)这个条件才进行sketch“
--------------------------------------------------------------------------------------------------------

你看下这个条件是否满足，如果满足是不应该会出现问题的. 否则在分类网络上在高剪枝率下也应该要有这个问题才对。

**Comment by lmbxmu** [comment]
> 你好呀作者，我是把你的代码用在了其他非分类模型的剪枝上，使用时并没有修改你的sketch_martrix函数。 刚才说的那个问题，我感觉更有可能是程序无法从640个卷积核丢掉320个卷积核？？？ 因为当我把程序改为从640个卷积核，剪到剩下480个卷积核时，程序不会报错。 如果是剩下320个卷积，就会报错。 我还尝试随机生成一个张量，去使用sketch_martrix函数，如果剪的比例太大，也会出现这个问题。 想问一下，大佬是否有修改程序解决这种问题的好办法？

linmb007 加我微信把错误截图发我看下
